using System.Text.Json.Serialization;

namespace VirtualController.Core.Devices;

/// <summary>Response curve applied to a calibrated axis value (-1.0 .. 1.0 or 0.0 .. 1.0) before output.
/// Changes sensitivity across the deflection range, not the calibrated range itself (see
/// <see cref="InputSettings.CalibratedMin"/> and related properties).</summary>
public enum AxisCurveType
{
    /// <summary>Unchanged, one-to-one mapping of the calibrated value (default).</summary>
    Linear,

    /// <summary>output = sign(x) * |x|^Exponent. Exponent &gt; 1 reduces sensitivity near the center and
    /// increases it near the extremes; exponent &lt; 1 increases sensitivity near the center.</summary>
    Exponential,

    /// <summary>Smooth S-shaped transition around the center (cubic Hermite interpolation), with reduced
    /// sensitivity near zero and a steeper response near the extremes.</summary>
    SCurve
}

/// <summary>
/// Settings for one physical input (button, axis direction, slider, or D-pad direction) on a device. Its key
/// in the parent <see cref="DeviceSettings.Inputs"/> dictionary is generated by
/// <see cref="PhysicalInputCatalog.BuildStorageKey"/>, so settings remain valid independently of which virtual
/// controller the device is assigned to.
/// </summary>
public sealed class InputSettings
{
    /// <summary>User-provided display name, replacing the default from <see cref="PhysicalInputCatalog"/>.
    /// Null/empty uses the default name.</summary>
    public string? CustomName { get; set; }

    /// <summary>When false, this input is ignored by automatic capture (<see cref="InputCaptureService"/>) and
    /// mapping evaluation (<see cref="Mapping.MappingEngine"/>), but remains visible and dimmed in the
    /// configuration dialog for renaming/calibration.</summary>
    public bool Enabled { get; set; } = true;

    /// <summary>For axes/sliders only: minimum raw value measured by the calibration assistant. Null means no
    /// calibration was performed and the normalized default range from the <see cref="IDeviceReader"/> applies.</summary>
    public float? CalibratedMin { get; set; }

    /// <summary>For axes/sliders only: maximum raw value measured by the calibration assistant.</summary>
    public float? CalibratedMax { get; set; }

    /// <summary>For centered axes (sticks) only: resting position measured by the calibration assistant when
    /// the physical center is not exactly zero due to component tolerances.</summary>
    public float? CalibratedCenter { get; set; }

    /// <summary>For axes/sliders only: deflection within this radius around the center is treated as zero
    /// (0.0 .. 1.0, device-wide; mapping always uses the current device-wide value). Can be set manually or
    /// estimated automatically through deadzone calibration (stick drift detection).</summary>
    public float Deadzone { get; set; }

    /// <summary>For axes/sliders only: response curve applied to the calibrated, deadzone-adjusted value
    /// before it is passed to mapping.</summary>
    public AxisCurveType CurveType { get; set; } = AxisCurveType.Linear;

    /// <summary>Exponent for <see cref="AxisCurveType.Exponential"/> (typically 1.5 .. 3.0) or strength of the
    /// S-curve for <see cref="AxisCurveType.SCurve"/> (typically 1.0 .. 3.0). Unused for
    /// <see cref="AxisCurveType.Linear"/>.</summary>
    public float CurveStrength { get; set; } = 1f;
}

/// <summary>
/// Settings for a complete physical device, independent of its current virtual controller assignment. The key
/// in the parent <see cref="Mapping.AppProfile.DeviceSettings"/> dictionary is
/// <see cref="PhysicalDeviceInfo.DeviceId"/>.
/// </summary>
public sealed class DeviceSettings
{
    /// <summary>When false, this device no longer appears in virtual controller device selections. The app
    /// filters it from selection lists regardless of its connection status.</summary>
    public bool Enabled { get; set; } = true;

    /// <summary>When true, the user manually hides this device completely. It leaves the main Device
    /// Configuration list (and appears in a separate collapsible list for restoration) and is removed from
    /// virtual controller selections, like a disabled device. This is independent of <see cref="Enabled"/>,
    /// preserving the prior enabled state when restored. Intended for devices that are permanently irrelevant,
    /// such as this app's ViGEmBus-emulated virtual controllers, which XInput/DirectInput cannot distinguish
    /// from physical hardware.</summary>
    public bool Hidden { get; set; }

    /// <summary>Last known display name for this device, updated after each successful detection. Used to show
    /// a meaningful name instead of the raw <see cref="PhysicalDeviceInfo.DeviceId"/> in the mapping table
    /// while the device is disconnected (e.g. when loading a profile).</summary>
    public string? LastKnownDisplayName { get; set; }

    /// <summary>Last known device capabilities (API, slot, buttons, POV, axes), updated after each successful
    /// detection (see <see cref="MainViewModel.RefreshDevices"/>). Used to reconstruct a synthetic disconnected
    /// <see cref="PhysicalDeviceInfo"/> for the Device Configuration tab so previously known devices remain
    /// visible and configurable while disconnected (see <see cref="MainViewModel.GetAllKnownDevices"/>).
    /// <see cref="LastKnownButtonCount"/> indicates whether complete capabilities have ever been recorded;
    /// without it, the device is not treated as known but disconnected.</summary>
    public InputApi? LastKnownApi { get; set; }

    public int? LastKnownApiSlot { get; set; }

    public int? LastKnownButtonCount { get; set; }

    public bool? LastKnownHasPov { get; set; }

    public List<PhysicalAxisId>? LastKnownAvailableAxes { get; set; }

    /// <summary>Settings per physical input, keyed by <see cref="PhysicalInputCatalog.BuildStorageKey"/>.
    /// Serialization omits axis/slider-only fields (calibration, deadzone, response curve) for digital inputs
    /// such as buttons and D-pad directions (see <see cref="InputSettingsDictionaryConverter"/>).</summary>
    [JsonConverter(typeof(InputSettingsDictionaryConverter))]
    public Dictionary<string, InputSettings> Inputs { get; set; } = new();

    /// <summary>User-defined display names for combined 2D sticks (e.g. "Left stick" -> "Flight stick"), keyed
    /// by <see cref="PhysicalInputCatalog.BuildStickStorageKey"/> (the stick's X-axis index). Separate from
    /// <see cref="InputSettings.CustomName"/> because a stick is not a physical input of its own, but a grouping
    /// of two axes in the configuration dialog (see <see cref="DeviceConfigStickGroupViewModel"/>).</summary>
    public Dictionary<string, string> StickNames { get; set; } = new();
}

/// <summary>
/// Extension methods for evaluating <see cref="DeviceSettings"/>, shared by
/// <see cref="Mapping.MappingEngine"/> and <see cref="InputCaptureService"/> so physical inputs disabled in
/// the configuration dialog are consistently ignored by both mapping and capture.
/// </summary>
public static class DeviceSettingsExtensions
{
    /// <summary>Checks whether a physical input is enabled. Missing entries (device/input never configured)
    /// default to enabled so existing profiles without <see cref="DeviceSettings"/> continue to work unchanged.</summary>
    public static bool IsInputEnabled(
        this IReadOnlyDictionary<string, DeviceSettings>? deviceSettings,
        string deviceId,
        PhysicalInputKind kind,
        int index)
    {
        if (deviceSettings is null || !deviceSettings.TryGetValue(deviceId, out var settings))
        {
            return true;
        }

        var key = PhysicalInputCatalog.BuildStorageKey(deviceId, kind, index);
        return !settings.Inputs.TryGetValue(key, out var inputSettings) || inputSettings.Enabled;
    }

    /// <summary>Returns an input's <see cref="InputSettings"/> (calibration, deadzone, response curve, custom
    /// name, enabled state), or null if the device/input has never been configured. Used by
    /// <see cref="Mapping.MappingEngine"/> to apply calibration and response curves before mapping an axis value.</summary>
    public static InputSettings? TryGetInputSettings(
        this IReadOnlyDictionary<string, DeviceSettings>? deviceSettings,
        string deviceId,
        PhysicalInputKind kind,
        int index)
    {
        if (deviceSettings is null || !deviceSettings.TryGetValue(deviceId, out var settings))
        {
            return null;
        }

        var key = PhysicalInputCatalog.BuildStorageKey(deviceId, kind, index);
        return settings.Inputs.TryGetValue(key, out var inputSettings) ? inputSettings : null;
    }

    /// <summary>Fallback when no device-wide calibration (<see cref="InputSettings.Deadzone"/>) exists for a
    /// physical axis. Used, for example, by <see cref="Mapping.MappingEngine.IsPhysicalInputActive"/> to detect
    /// activity for toggle/on-off triggers.</summary>
    public const float DefaultAxisDeadzoneWithoutCalibration = 0.025f;

    /// <summary>Resolves the current deadzone for a physical axis. Returns its device-wide calibration
    /// (<see cref="InputSettings.Deadzone"/>) when present, otherwise
    /// <see cref="DefaultAxisDeadzoneWithoutCalibration"/>. Like
    /// <see cref="Mapping.MappingEngine.ApplyAxisSource"/>, always uses the canonical AxisPositive key for
    /// that axis index, regardless of the captured direction.</summary>
    public static float ResolveDefaultAxisDeadzone(
        this IReadOnlyDictionary<string, DeviceSettings>? deviceSettings,
        string deviceId,
        int axisIndex)
    {
        var axisSettings = deviceSettings.TryGetInputSettings(deviceId, PhysicalInputKind.AxisPositive, axisIndex);
        return axisSettings?.Deadzone ?? DefaultAxisDeadzoneWithoutCalibration;
    }

    /// <summary>Returns the <see cref="InputSettings"/> for a physical input on a device, creating it if needed
    /// (unlike <see cref="TryGetInputSettings"/>, which returns null when missing). Used by device configuration
    /// so every catalogued input, including axes in the live visualization, has a persistable settings instance
    /// as soon as the dialog displays it.</summary>
    public static InputSettings GetOrCreateInputSettings(
        this DeviceSettings settings,
        string deviceId,
        PhysicalInputKind kind,
        int index)
    {
        var key = PhysicalInputCatalog.BuildStorageKey(deviceId, kind, index);
        if (!settings.Inputs.TryGetValue(key, out var inputSettings))
        {
            inputSettings = new InputSettings();
            settings.Inputs[key] = inputSettings;
        }

        return inputSettings;
    }
}
