blank_issues_enabled: true
contact_links:
  - name: Question / discussion
    url: https://github.com/ssk-dev/VirtualController/discussions
    about: For general questions or discussion that aren't a bug report or feature request, please use GitHub Discussions (if enabled) instead of an issue.
